---
- hosts: waf-blue:waf-green
  gather_facts: no
  roles:
    - role: waf-bootstrap
    - role: waf-config

- hosts: web:sql
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - role: common
    - role: docker

- hosts: web:sql
  gather_facts: no
  become: yes
  become_method: sudo
  strategy: free
  tasks:
  - include_role: 
      name: badstore
    when:  "'web' in group_names"
#  - include_role: 
#      name: dvwa
#    when:  "'web' in group_names"
  - include_role: 
      name: colors
    when:  "'web' in group_names"
  - include_role: 
      name: portal
    when:  "'web' in group_names"
  - include_role: 
      name: sql
    when: "'sql' in group_names"
