---
- hosts: web:sql
  gather_facts: no
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - role: common
    - role: docker

- hosts: web:sql
  gather_facts: no
  become: yes
  become_method: sudo
  strategy: free
  tasks:
  - include_role: 
      name: colors
    when:  "'web' in group_names"
  - include_role: 
      name: sql
    when: "'sql' in group_names"

- hosts: waf-blue:waf-green
  gather_facts: no
  roles:
    - role: waf-bootstrap

- hosts: waf-blue:waf-green
  gather_facts: no
  roles:
    - role: waf-config
